/**
 * Global constants used throughout the application.
 * Never hardcode these values anywhere else.
 */
const CONSTANTS = {

  SPREADSHEET_ID: "1biQZJdxEoR-R26LixTAadSgRFNaItfu9BD_VnQJozT4",

  SHEETS: {

    APPLICATIONS: "Applications",

    CONFIG: "Config",

    SENDER_ACCOUNTS: "SenderAccounts",

    COMPANIES: "Companies",

    LOGS: "Logs",

    DASHBOARD: "Dashboard",

    SYSTEM: "System",

    WORKER_STATUS: "WorkerStatus"

  },

  WORKER_STATUS_COLUMNS: {

    SENDER: 1,
    STATUS: 2,
    LAST_HEARTBEAT: 3,
    CURRENT_COMPANY: 4,
    SENT_TODAY: 5,
    LAST_ERROR: 6,
    LAST_ACTIVITY: 7

  },

  STATUS: {

    NEW: "NEW",

    CLAIMED: "CLAIMED",

    DRAFT_CREATED: "DRAFT_CREATED",

    SENT: "SENT",

    REPLIED: "REPLIED",

    BOUNCED: "BOUNCED",

    FAILED: "FAILED",

    CLOSED: "CLOSED"

  },
  
  TERMINAL_STATUSES: [

    CONSTANTS.STATUS.REPLIED,

    CONSTANTS.STATUS.BOUNCED,

    CONSTANTS.STATUS.FAILED,

    CONSTANTS.STATUS.CLOSED

],

  RECIPIENT_TAG: {

    RECRUITER: "Recruiter",

    HIRING_MANAGER: "Hiring Manager",

    REFERRAL: "Referral",

    EXECUTIVE: "Executive"

  },

  CONFIG_KEYS: {

    GEMINI_API_KEY: "GEMINI_API_KEY",

    GEMINI_MODEL: "GEMINI_MODEL",

    MODE: "MODE",

    RESUME_FILE_ID: "RESUME_FILE_ID",

    MAX_RETRIES: "MAX_RETRIES",

    MAX_OUTPUT_TOKENS: "MAX_OUTPUT_TOKENS",

    TEMPERATURE: "TEMPERATURE",

    DAILY_EMAIL_LIMIT: "DAILY_EMAIL_LIMIT",

    RANDOM_DELAY_MIN: "RANDOM_DELAY_MIN",

    RANDOM_DELAY_MAX: "RANDOM_DELAY_MAX",

    GMAIL_LABEL: "GMAIL_LABEL",

    EMAIL_DELAY_MIN: "EMAIL_DELAY_MIN",

    EMAIL_DELAY_MAX: "EMAIL_DELAY_MAX",

    STARTUP_DELAY_MIN: "STARTUP_DELAY_MIN",

    STARTUP_DELAY_MAX: "STARTUP_DELAY_MAX",

    FOLLOW_UP_AFTER_DAYS: "FOLLOW_UP_AFTER_DAYS",

    MAX_FOLLOW_UPS: "MAX_FOLLOW_UPS",

    ENABLE_DUPLICATE_CHECK: "ENABLE_DUPLICATE_CHECK",

    EMAIL_SIGNATURE: "EMAIL_SIGNATURE",

    SENDER_EMAIL: "SENDER_EMAIL"

},

  MODE: {

    DRAFT: "DRAFT",

    AUTO_SEND: "AUTO_SEND"

  },

  QUEUE: {

  CLAIM_TIMEOUT_MINUTES: 5

  }

};